### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mxnmnm** [ITsMrToad/PalladiumMod#11]
I loaded palladium 1.0.0 on my forge server and it crashed :(

Here is the report: https://gist.github.com/mxnmnm/35f4665801773380a7d07396121130d3

**Comment by ITsMrToad** [comment]
Palladium is a partially client-side mod. Any client-side mods (even such as starlight) should not be on the server-side.

**Comment by mxnmnm** [comment]
Oh I saw the tps improvements on the modrinth page so I thought there was a server side element to it.

**Comment by ITsMrToad** [comment]
Palladium is partially server-side.

**Comment by mxnmnm** [comment]
So doesn't that mean it should work server-side with the client stuff disabled? What are the server-side aspects of it anyways?

**Comment by ITsMrToad** [comment]
Not all server values can be disabled in the config.

**Comment by mxnmnm** [comment]
So there's no way to get the server-side benefits on a dedicated server?

**Comment by ITsMrToad** [comment]
> So there's no way to get the server-side benefits on a dedicated server?

Not at the moment, but maybe in 1.0.2, I will add a special config to disable the client-side

**Comment by ITsMrToad** [comment]
Palladium cannot be made server-side at the moment. Config uses ``gameDirectory`` field, which ```Minecraft.class``` (client class).
