### ISSUE TITLE
Incompatibility with Dynamic Trees

### ISSUE THREAD

**Issue by iekiekkeikei** [ITsMrToad/PalladiumMod#14]
Cutting down a dynamic trees breaks the texture.

Looks normal until before the first logging.
But when you start logging, the texture breaks down…

Modlist
Palladium-1.20-1.20.4-1.0.1.jar
DynamicTrees-1.20.1-1.3.0-BETA14.jar
ToadLib-1.20-1.20.4-1.1.4.jar

debuglog
https://mclo.gs/gG5LNaq

![2024-09-02_19 28 18](https://github.com/user-attachments/assets/e0fb62ca-1a46-4e5d-bfe4-2cf293a200e8)
88dc6dc311)

**Comment by ITsMrToad** [comment]
Try disable 'shader_uniform_caching'.

**Comment by iekiekkeikei** [comment]
Setting enableQuadsDedup to false instead of shader_uniform_caching fixed it.

**Comment by ITsMrToad** [comment]
Fixed in 1.0.2
