### ISSUE TITLE
1.20.1 Forge [Palladium/]: Failed replace entity

### ISSUE THREAD

**Issue by Krimatoria** [ITsMrToad/PalladiumMod#16]
ToadLib-1.20-1.20.4-1.1.5.jar
Palladium-1.20-1.20.4-1.0.2.jar
There is basically no settings file in the config folder, maybe that's why?

**Comment by ITsMrToad** [comment]
Are there any irregularities in the behavior of entities?

**Comment by Krimatoria** [comment]
> Are there any irregularities in the behavior of entities?

Yes, I'm still testing mods for FPS TPS. I'll take a look now when I launch the world)

**Comment by Krimatoria** [comment]
I haven't seen any problems so far, but I'm still testing, but the menu setting is missing Embeddium

**Comment by Krimatoria** [comment]
1000 Messages, it keeps clogging up the log
![image](https://github.com/user-attachments/assets/822549db-a44d-4c9a-85dc-a9ff3b011193)

![image](https://github.com/user-attachments/assets/ce6cb521-ef7c-4ae8-969f-7e9c71e7cd1e)

**Comment by ITsMrToad** [comment]
Send a full list of mods.

**Comment by ITsMrToad** [comment]
idk why the config file is not created in 1.0.2, I'll try to fix it in 1.0.3, for now, you can use 1.0.1.

**Comment by ITsMrToad** [comment]
Fixed in 1.0.3.
