### ISSUE TITLE
Bugged textures with Create

### ISSUE THREAD

**Issue by Daniel366Cobra** [ITsMrToad/PalladiumMod#17]
Some Create block textures bugged (andesite casing, gearboxes, connected multiblocks like fluid tanks and item vaults) and display random parts of texture sheet.
Link to Palladium found by disabling mods one by one.

MC Version: 1.20.1 Forge
Palladium version: 1.0.1
Mods: Oculus, Xenon, Radium, Ferrite Core, Entity Culling; Create & addons; Macaw's mods; QoL stuff like Xaero's maps, JEI, WTHIT with Megane; worldgen mods (Terralith + Tectonic).

**Comment by ITsMrToad** [comment]
Try disable quad deduplication.

**Comment by Daniel366Cobra** [comment]
> Try disable quad deduplication.

I feel dumb but I cannot find a dedicated config for Palladium or a respective option in Xenon, Oculus or current shaderpack configs.

**Comment by ITsMrToad** [comment]
Try searching for ```Model verticies deduplication```

**Comment by Daniel366Cobra** [comment]
> Try searching for `Model verticies deduplication`

Sorry but where exactly should I search for it? There is no dedicated Palladium config file in my config folder, and going through Oculus's video settings or shaderpack settings yields nothing like that.

**Comment by ITsMrToad** [comment]
> > Try searching for `Model verticies deduplication`
> 
> Sorry but where exactly should I search for it? There is no dedicated Palladium config file in my config folder, and going through Oculus's video settings or shaderpack settings yields nothing like that.

I didn't realize xenon didn't have in-game config. 

Install embeddium 0.3+ and go to 'graphics settings/deduplication'.

**Comment by Daniel366Cobra** [comment]
> > > Try searching for `Model verticies deduplication`
> > 
> > 
> > Sorry but where exactly should I search for it? There is no dedicated Palladium config file in my config folder, and going through Oculus's video settings or shaderpack settings yields nothing like that.
> 
> I didn't realize xenon didn't have in-game config.
> 
> Install embeddium 0.3+ and go to 'graphics settings/deduplication'.

That worked. Weird that xenon does not have a config.

**Comment by Krimatoria** [comment]
And Xenon doesn't have your settings in the graphics menu. Everything is fine in Embeddium. 

Is Xenon a problem on their side?
