### ISSUE TITLE
Client/Server

### ISSUE THREAD

**Issue by lanwoodall423** [ITsMrToad/PalladiumMod#18]
Should this mod only be present on the client when using a dedicated server? Will it cause issues if being used client side only with a dedicated server?

**Comment by ITsMrToad** [comment]
> Should this mod only be present on the client when using a dedicated server? Will it cause issues if being used client side only with a dedicated server?

I don't know exactly. 0.9.9 for fabric/quilt will most likely be able to work without issues on the client side.
