### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AkitaEllie** [ITsMrToad/PalladiumMod#19]
The mod initially worked, until it crashed on any world load, this is on two different worlds, and one new world
Worlds : 
https://paste.gg/p/anonymous/0625a013105a43c7b34d1ff7b43db05e
https://paste.gg/p/anonymous/0037ce8578c64dd3acac867fb6da9640

New world : 
https://paste.gg/p/anonymous/7a6e1f5aac9d464988f3c67022b3209b

I will attempt to eliminate mod conflicts next

**Comment by ITsMrToad** [comment]
Try remoove carpet or disable the “Improved flee AI of mobs” option

**Comment by AkitaEllie** [comment]
that solved it, much thanks!
