### ISSUE TITLE
FerriteCore

### ISSUE THREAD

**Issue by ghost** [ITsMrToad/PalladiumMod#2]
When running with the “FerriteCore” mod, the game does not start. Conflict of mods

**Comment by ghost** [comment]
also crashes with the radium mod

**Comment by ITsMrToad** [comment]
Send the crash log

**Comment by ghost** [comment]
[ferrute](https://github.com/user-attachments/files/16657884/latest.log)
[radium](https://github.com/user-attachments/files/16657891/latest.log)

There's no other logs, just these last ones.

**Comment by ITsMrToad** [comment]
There is too little information to help you with it. Are there definitely no other logs? Check along the path `.minecraft/crash_reports`.

**Comment by ghost** [comment]
no crash log. Try testing it yourself. I'm crashing the game for some reason

**Comment by ITsMrToad** [comment]
Try update palladium to 0.9.8

**Comment by ghost** [comment]
okay, thx
