### ISSUE TITLE
[1.20.1] lots of mobs capable of hurting one another do so unprovoked

### ISSUE THREAD

**Issue by kuba26038** [ITsMrToad/PalladiumMod#20]
i've seen mobs such as strays, skeletons, zombies and for some reason even dolphins attacking one another unprovoked. this doesn't occur for all mobs, though, iron golems for an instance don't do anything to one another, as far as i've tested. i'm pretty sure this is unintended behavior. this happens even when only palladium and toadlib are installed

https://github.com/user-attachments/assets/8b94351e-5ce6-411f-9957-f9a3eaee50e7

(i am not sorry for the watermark)

**Comment by EnvyInvidia** [comment]
I would like to add that I've also encountered the same issue—every hostile/neutral mob attacks each other for some reason.

**Comment by ITsMrToad** [comment]
What loader are you using?

**Comment by Shahubk** [comment]
Also having the same issue on Palladium 1.0.3 using forge 47.3.10 through Prism Launcher.

**Comment by ITsMrToad** [comment]
This will be fixed in 1.0.4. 
Perhaps disabling “Improved Target Finder for Mobs” will help resolve this for now

**Comment by ITsMrToad** [comment]
1.0.4 is out for fabric/forge/neoforge

**Comment by Krimatoria** [comment]
> i've seen mobs such as strays, skeletons, zombies and for some reason even dolphins attacking one another unprovoked. this doesn't occur for all mobs, though, iron golems for an instance don't do anything to one another, as far as i've tested. i'm pretty sure this is unintended behavior. this happens even when only palladium and toadlib are installed
> 
>  2024-09-14-20-43-42_rm6b7x2P.mp4 
> (i am not sorry for the watermark)

Oh, yes, I had it too, I'll update the mod and take a look
