### ISSUE TITLE
[1.20.1] textiles from Hexerei have their texture turned into clown vomit

### ISSUE THREAD

**Issue by kuba26038** [ITsMrToad/PalladiumMod#21]
the mod hexerei adds a block called "infused fabric".  with this mod installed i've noticed that all of it's types have it's textures replaced with something that is commonly referred to as "clown vomit". here are two examples, the first of which i've seen when having over 300 various mods installed, while the second one i've seen with only hexerei, toadlib and palladium in the mods folder.
![2024-09-14_20 17 17](https://github.com/user-attachments/assets/5b54648b-c3ad-4220-a2a1-48ebcc968f90)
![2024-09-14_20 42 45](https://github.com/user-attachments/assets/fa3960c6-d532-485a-82ea-526b24633927)

**Comment by Krimatoria** [comment]
> the mod hexerei adds a block called "infused fabric". with this mod installed i've noticed that all of it's types have it's textures replaced with something that is commonly referred to as "clown vomit". here are two examples, the first of which i've seen when having over 300 various mods installed, while the second one i've seen with only hexerei, toadlib and palladium in the mods folder. ![2024-09-14_20 17 17](https://private-user-images.githubusercontent.com/81324988/367538293-5b54648b-c3ad-4220-a2a1-48ebcc968f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNDM5MjMsIm5iZiI6MTcyNjM0MzYyMywicGF0aCI6Ii84MTMyNDk4OC8zNjc1MzgyOTMtNWI1NDY0OGItYzNhZC00MjIwLWEyYTEtNDhlYmNjOTY4ZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE5NTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGMxZTI3OWMyZDc1ZjUzNjc5ODAxOTVlYWRmYzAwYzQ5YzZhNWYwN2I4Y2VkMTgyOGU5ZTlmNWIyNDFjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpdmh8FrZELYILRdd9X-6gn56HnbdGtNoWYNmHSDQl0) ![2024-09-14_20 42 45](https://private-user-images.githubusercontent.com/81324988/367538298-fa3960c6-d532-485a-82ea-526b24633927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNDM5MjMsIm5iZiI6MTcyNjM0MzYyMywicGF0aCI6Ii84MTMyNDk4OC8zNjc1MzgyOTgtZmEzOTYwYzYtZDUzMi00ODVhLTgyZWEtNTI2YjI0NjMzOTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE5NTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTI3ZTMyZDRjZDA1NzlhZDZlZDRlOWM1MDVmNzg0NGJjNTE0YjU2ZGRhZjFlMmM3ZmNmZGJmMzY0YTRhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRWYMPicF_L3wsjeixdIOfzoKoB25RB0JlBsMWtTc90)

Oh, I had a similar one, but I didn't know which mod, it looked different with shaders

**Comment by Krimatoria** [comment]
Oh, I had a similar one, but I didn't know which mod, it looked different with shaders

**Comment by ITsMrToad** [comment]
Disable 'Model verticies deduplication' option.
