### ISSUE TITLE
Suggestion 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [ITsMrToad/PalladiumMod#22]
You already have AI improvements in mod for wolves and cats, maybe you can do it for chickens, they have always had a very bad effect on TPS.
![2024-09-14_22 45 58](https://github.com/user-attachments/assets/db2da210-a1fc-4625-9ceb-338a3d11837d)

**Comment by ITsMrToad** [comment]
What is this mod? it might help me in the future.

**Comment by Krimatoria** [comment]
> What is this mod? it might help me in the future.

[spark](https://modrinth.com/mod/l6YH9Als) + [Observable](https://modrinth.com/mod/VYRu7qmG) 😊

**Comment by ITsMrToad** [comment]
Thanks. I'll do something about the chickens.

**Comment by ITsMrToad** [comment]
I did a test using observable and my chickens have normal TPS.


![2024-09-16_22 14 05](https://github.com/user-attachments/assets/6d545768-f95f-4fd6-9b23-92575d75e085)

**Comment by Krimatoria** [comment]
> I did a test using observable and my chickens have normal TPS.
> 
> ![2024-09-16_22 14 05](https://private-user-images.githubusercontent.com/121745579/367856477-6d545768-f95f-4fd6-9b23-92575d75e085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDg1MTcsIm5iZiI6MTcyNjUwODIxNywicGF0aCI6Ii8xMjE3NDU1NzkvMzY3ODU2NDc3LTZkNTQ1NzY4LWY5NWYtNGZkNi05YjIzLTkyNTc1ZDc1ZTA4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxNzM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDZkYzQyOTNhNmIzYTU4OTIzZDdmODVkNDE0ODFmMmJmMzlmNWZlOGFhZTViZGNmY2ZjMDM3MzFlNmE3YTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkbqixLCS0EdjQF7_8nGUlpUZJFwUArfoQyslC18NS0)

I'll look later only in vanilla, but it seems to me that you need to look in regular generation too.

**Comment by ITsMrToad** [comment]
The image is not loading.


>  in regular generation.

Ok. I'll try...
