### ISSUE TITLE
[1.20.1] Mod causes startup to fail on a dedicated server

### ISSUE THREAD

**Issue by PoeticRainbow** [ITsMrToad/PalladiumMod#23]
When installed on a dedicated server the mod causes an ambiguous crash.

`[14Sep2024 22:40:53.252] [main/WARN] [mixin/]: Error loading class: org/apache/commons/codec/binary/Base64 (java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64)`

Forge 1.20.1-47.3.0
Palladium 1.20-1.20.4-1.0.3
ToadLib-1.20-1.20.4-1.1.5

**Comment by ITsMrToad** [comment]
The mod is not server-side, it requires both sides to work

**Comment by PoeticRainbow** [comment]
The server doesn't start with it installed -- are you meaning to say it's client only?

**Comment by ITsMrToad** [comment]
No, Palladium requires BOTH sides to work, client and server

**Comment by ToppyTopology** [comment]
> No, Palladium requires BOTH sides to work, client and server

I can confirm that installing the mod in a server will crash with that error. I wanted to clarify that what he meant was that the server would crash on its own even before the server fully initialize, when it really shouldn't.  

if a client does join the sever without the mod, it should certainly not crash the server but instead just not allow the player to join, nonetheless this is an unrelated issue

**Comment by KateReller** [comment]
I am also getting this same exact error when launching my NOT CLIENT, DEDICATED SERVER with this mod. I don't understand what the author means since the mod crashes on the *server* side when it's installed.
