### ISSUE TITLE
Lag when searching for items in Creative Menu

### ISSUE THREAD

**Issue by JuiceyBeans** [ITsMrToad/PalladiumMod#26]
https://github.com/user-attachments/assets/809b3102-5548-4f27-8f53-576b85a1c824
Does not occur without Palladium installed

FPS tanks to as low as 7FPS when searching for items in the creative menu (video attached)

Mods installed: Embeddium, KubeJS, GregTech 1.4.1, Palladium

**Comment by ITsMrToad** [comment]
Disable 'Model Verticies deduplication' option
