### ISSUE TITLE
Wolf Path-Finding Crash on Minecraft 1.21 , Palladium 1.0.5

### ISSUE THREAD

**Issue by MylesGit** [ITsMrToad/PalladiumMod#29]
There seems to be another [issue](https://github.com/ITsMrToad/PalladiumMod/issues/25) open for an older version of Minecraft that also crashes due to path-finding ai changes in Palladium. 

If you aren't able to figure anything out from this log I'll create a new instance and sift through all my mods to narrow it down. Just let me know in this issue.

[See log here.](https://mclo.gs/QzUdhyX)

**Comment by ITsMrToad** [comment]
> I'll create a new instance and sift through all my mods to narrow it down

Yeah, that would be nice.

So far, all I see is that accesswidener can't make public minecraft classes for some reason.

**Comment by MylesGit** [comment]
This issue is purely Palladium. When loading into a world with a wolf loaded (or spawning one in), it will crash the game. This is not a mod conflict as I am reproducing this with just Fabric API, Palladium, and ToadLib. 

[Here is the log.](https://mclo.gs/v60xE6D)

**Comment by ITsMrToad** [comment]
Well, I'll fix it, for now, disable the “Improved target search for mobs” and “Improved flee AI of mobs” options.

**Comment by ITsMrToad** [comment]
Fixed in 1.0.6.
