### ISSUE TITLE
The Black World

### ISSUE THREAD

**Issue by K0rS1z** [ITsMrToad/PalladiumMod#3]
When using the "Shader uniform caching" parameter, everything in the world turns black. IMPORTANT: if you run the game (not the world) with the parameter ENABLED, then there will be such an effect. If you run it with the parameter DISABLED, then there will be no such effect.
As I understand it, everything happens when the world is loaded.

https://imgur.com/a/1R5ThNT (The video weighs a lot)

Minecraft - 1.20.1
Forge - 47.3.0
Mods:
embeddium-0.3.30+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
Palladium-0.9.4B-1.20.1.20.4.jar
ToadLib-1.20-1.20.4-1.1.0.jar

**Comment by K0rS1z** [comment]
[latest.log](https://github.com/user-attachments/files/16658869/latest.log)

**Comment by ITsMrToad** [comment]
I found traces of fabric in the log - `[16:50:10] [Render thread/WARN]: Error loading class: net/fabricmc/fabric/api/blockview/v2/FabricBlockView (java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockview.v2.FabricBlockView)
[16:50:10] [Render thread/WARN]: Error loading class: net/fabricmc/fabric/api/rendering/data/v1/RenderAttachedBlockView (java.lang.ClassNotFoundException: net.fabricmc.fabric.api.rendering.data.v1.RenderAttachedBlockView)`. What is it?

**Comment by K0rS1z** [comment]
> I found traces of fabric in the log - `[16:50:10] [Render thread/WARN]: Error loading class: net/fabricmc/fabric/api/blockview/v2/FabricBlockView (java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockview.v2.FabricBlockView) [16:50:10] [Render thread/WARN]: Error loading class: net/fabricmc/fabric/api/rendering/data/v1/RenderAttachedBlockView (java.lang.ClassNotFoundException: net.fabricmc.fabric.api.rendering.data.v1.RenderAttachedBlockView)`. What is it?

1. I do not know where these lines come from. The log is which mod creates them if there are only 4 of them...
2. And I also found the reason for the bug: The graphics are Fabulous!
Everything is fine for the rest.

**Comment by ITsMrToad** [comment]
Fixed in 0.9.9
