### ISSUE TITLE
Palladium 10.4 forge bug

### ISSUE THREAD

**Issue by ghost** [ITsMrToad/PalladiumMod#30]
There are distortions in the graphics in Palladium 10.4 Forge Sahane graphics mode. TNT explosion sounds can be heard near the villages. There are distortions in the water.
![Screenshot_20240917_211159_Fold Craft Launcher](https://github.com/user-attachments/assets/bfd18840-6d1c-45fb-84ab-bd313a034d1a)
![Screenshot_20240917_211229_Fold Craft Launcher](https://github.com/user-attachments/assets/d8d7cec1-1ef0-4491-a3f5-0fe30ee901a8)
![Screenshot_20240917_211312_Fold Craft Launcher](https://github.com/user-attachments/assets/54b1598d-9062-41fe-a3b9-cff260feb786)
![Screenshot_20240917_211355_Fold Craft Launcher](https://github.com/user-attachments/assets/a689721f-b705-4b9a-96a9-c0e4d2c7fc6c)
![Screenshot_20240917_211517_Fold Craft Launcher](https://github.com/user-attachments/assets/b47ee087-0da4-4a29-a306-3c31712588cb)
![Screenshot_20240917_211327_Fold Craft Launcher](https://github.com/user-attachments/assets/318f64df-e93d-4a99-b9a7-3e637d1a2876)

only in mods with palladium and toast lib attached

**Comment by ITsMrToad** [comment]
Emmm... Is it minecraft java on mobile?

**Comment by ghost** [comment]
There is fold craft launcher on mobile, you can play minecraft java on android with it. I don't think the errors are because I use an emulator.

**Comment by ITsMrToad** [comment]
Sorry, but Palladium doesn't support different mobile ports, due to the fact that I didn't assume you would use it that way, and also because I can't reproduce the issue.

**Comment by ghost** [comment]
I will install Minecraft on the computer and see if I can recreate the problem. If I can recreate the problem or not, I will write here.
