### ISSUE TITLE
Bamboo blocks light as if it were a full block

### ISSUE THREAD

**Issue by VindSole** [ITsMrToad/PalladiumMod#34]
Latest version
![2024-09-19_12 06 03](https://github.com/user-attachments/assets/ad5e9d64-0b20-4aab-8a7f-e58ebcd0772d)

Vanilla
![2024-09-19_12 06 31](https://github.com/user-attachments/assets/78eb743e-000a-4034-b802-373c9fc1c9f0)

**Comment by ITsMrToad** [comment]
Fixed in 1.0.7

**Comment by NattoRiisa** [comment]
can this be released on 1.21? :o
