### ISSUE TITLE
1.21.x source code

### ISSUE THREAD

**Issue by Steveplays28** [ITsMrToad/PalladiumMod#35]
Hi, where can I find the 1.21.x source code?
The only branch listed is 1.20-1.20.4.

Also, on Fabric the resource reload listener is never registered, thus resulting in the deduplication never happening.
Either way, this seems like a cool mod, good work!

**Comment by ITsMrToad** [comment]
> Hi, where can I find the 1.21.x source code?

The source code for palladium 1.21x is not yet available, but it will be soon.

> Also, on Fabric the resource reload listener is never registered, thus resulting in the deduplication never happening.

I haven't registered it as I don't know how to do that. Instead of ResourceReloadListener I used mixins.

> this seems like a cool mod, good work!

Thanks!

**Comment by Steveplays28** [comment]
> I haven't registered it as I don't know how to do that. Instead of ResourceReloadListener I used mixins.

That works, I missed that when looking through the mod.

This is an example of registering a resource reload listener using Fabric's `ResourceManagerHelper`:
[Fabric example](https://github.com/steves-underwater-paradise/simple-seasons/blob/d2831d1d60f608ace0f41894cedab5887b21717b/src/main/java/io/github/steveplays28/simpleseasons/client/SimpleSeasonsClient.java#L41)

**Comment by ITsMrToad** [comment]
Oh, thank you. I'll be sure to use that in the future.
