### ISSUE TITLE
Create Textures Break with Palladium Enabled

### ISSUE THREAD

**Issue by GalacticSpike** [ITsMrToad/PalladiumMod#36]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

When Palladium and Create are both enabled, Create's textures will become bugged, either changing to another texture, going black, or getting scrambled.  
![Palladium and Create texture bug](https://github.com/user-attachments/assets/c012ffe8-baf4-4059-9abc-47217a1ca0f9)

### Steps to reproduce

Place any create block which uses a standard block mode and connected textures while palladium is enabled and the textures will change.

### What version of the palladium are you using?

Palladium-1.20-1.20.4-1.0.7

**Comment by ITsMrToad** [comment]
Try disable 'Model verticies deduplication'
