### ISSUE TITLE
Do you have any plans to make a mod releated to otimization of HDD or SSD?

### ISSUE THREAD

**Issue by SmilleCreeper** [ITsMrToad/PalladiumMod#37]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

It's a bit unreleated to Palladium mod you're developing in general, but my friend and some other people have very slow HDD. Essentially, my modpack optimized everything - CPU, RAM, Graphic Card, and it's working very well, considering it's a 600+ mod modpack and it run on very slow hardware. But also, it takes very much time to start, and I think the main reason is limit speed of HDD and certain SSD. Perhaps you could consider to find a workaround these limitations I'm facing right now? Thanks for the attention, btw. 

### What version of the palladium are you using?

Unreleated

**Comment by ITsMrToad** [comment]
The more optimization mods installed, the more load on HDD/SSD is likely to be(Most mods cache something one way or another, in palladium's case it's shaders and de-duplication). 

> But also, it takes very much time to start, and I think the main reason is limit speed of HDD and certain SSD

There is no way to optimize HDD/SDD as far as I know, but palladium has an option 'Disable data fixers'. You can enable it and restart the game, it will reduce the loading time a bit.

One more thing, if the issue topic is not bug/incompatibility related, you should create issue from blank-issue

**Comment by SmilleCreeper** [comment]
> The more optimization mods installed, the more load on HDD/SSD is likely to be(Most mods cache something one way or another, in palladium's case it's shaders and de-duplication).
> 
> > But also, it takes very much time to start, and I think the main reason is limit speed of HDD and certain SSD
> 
> There is no way to optimize HDD/SDD as far as I know, but palladium has an option 'Disable data fixers'. You can enable it and restart the game, it will reduce the loading time a bit.
> 
> One more thing, if the issue topic is not bug/incompatibility related, you should create issue from blank-issue

Yeah, sorry for confusion, it's just I'm relatively new to github and don't know much about how it works.

Regarding datafixers, they make loading world more fast, but not the game itself, no? I think HDD/SSD is a bottleneck, because it takes me 5 minutes to launch my modpack while my friend's PC launch it... well, 2-3 hours, really.

Maybe we can figure out something, though?

**Comment by ITsMrToad** [comment]
> Regarding datafixers, they make loading world more fast, but not the game itself, no?

They speed up the loading of both the world and the game.

> Maybe we can figure out something, though?

Again, I personally don't know how to optimize HDD/SSD performance. If you have any ideas, please suggest them.

**Comment by SmilleCreeper** [comment]
> > Regarding datafixers, they make loading world more fast, but not the game itself, no?
> 
> They speed up the loading of both the world and the game.
> 
> > Maybe we can figure out something, though?
> 
> Again, I personally don't know how to optimize HDD/SSD performance. If you have any ideas, please suggest them.

Hm... perhaps, it would be useful to have at least a mod that tells you which mods cause most loading lag. Something similar to spark, but not for CPU, but for HDD/SSD instead, and during loading, not during gameplay. Is it possible for you to make?

**Comment by ITsMrToad** [comment]
> Is it possible for you to make?

idk.
