### ISSUE TITLE
1.21 - NeoForge Support?

### ISSUE THREAD

**Issue by Cixon** [ITsMrToad/PalladiumMod#38]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

NeoForge

### Describe the bug

Title - Enchantment

Please add NeoForge support for 1.21 if possible! Have a good day!

### What version of the palladium are you using?

N/A

**Comment by ITsMrToad** [comment]
Version 1.21 neo coming soon!

Please, if your issue is not related to a bug/incompatibility, create a blank-issue.

**Comment by Cixon** [comment]
oh? awesome! 👀
