### ISSUE TITLE
Вопрос: Есть ли смысл использовать этот мод, если насколько я знаю что-то подобное есть в ModernFix

### ISSUE THREAD

**Issue by wicivo** [ITsMrToad/PalladiumMod#40]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

.

### What version of the palladium are you using?

.

**Comment by ITsMrToad** [comment]
В modern-fix существует де-дупликация ResourceLocation и Climate, в palladium ModelResourceLocation, ResourceLocation, Verticies, ResourceKey.

Также не стоит забывать о других возможностях palladium.

Для вопросов создавайте blank-issue.

**Comment by wicivo** [comment]
> В modern-fix существует де-дупликация ResourceLocation и Climate, в palladium ModelResourceLocation, ResourceLocation, Verticies, ResourceKey.
> 
> Также не стоит забывать о других возможностях palladium.
> 
> Для вопросов создавайте blank-issue.

Можете по подробнее рассказать что они делают и как влияют на производительность?

**Comment by ITsMrToad** [comment]
Все особенности описаны на modrinth.

**Comment by wicivo** [comment]
Ок, как я смогу воспроизвести это? https://cdn.modrinth.com/data/cached_images/33a5b8f599a3a0a1a9e377854979a3ed098accc6.png

**Comment by ITsMrToad** [comment]
Запустить ТОЛЬКО palladium и toadlib на forge 1.20.2. нагрузить ближайшую местность объектами(такими как сущности), сравнить показатели.

Результат может отличаться из-за разной конфигурации ПК.
