### ISSUE TITLE
Palladium doesn't work on servers

### ISSUE THREAD

**Issue by Dann50** [ITsMrToad/PalladiumMod#42]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

Palladium works on the client, but when on the server it crashes
[latest.log](https://github.com/user-attachments/files/17188682/latest.log)

### Steps to reproduce

Install 0.16.5 fabric server and install palladium, fabric api and toadlib. crash.

### What version of the palladium are you using?

Palladium-1.20-1.20.4-1.0.9.jar

**Comment by PoeticRainbow** [comment]
Said this in #23 and was brushed off.
