### ISSUE TITLE
Incompatible with Create

### ISSUE THREAD

**Issue by fzrdwa123456** [ITsMrToad/PalladiumMod#45]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

![屏幕截图 2024-10-04 182447](https://github.com/user-attachments/assets/2b7535c9-f002-4db3-b3dc-de0a17e9992d)

This can cause problems with some item textures in Create

### Steps to reproduce

Installing create and Palladium will do just that

### What version of the palladium are you using?

minecraft 1.20.1 Palladium 1.0.7

**Comment by ITsMrToad** [comment]
Try disable 'Model verticies deduplication'
