### ISSUE TITLE
villagers don't breed

### ISSUE THREAD

**Issue by ben0x539** [ITsMrToad/PalladiumMod#47]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric, NeoForge

### Describe the bug

Villagers don't breed despite having excess beds and plenty of food.

I noticed this in a Minecraft 1.21.1. Fabric 0.16.5 singleplayer game with some other mods, confirmed that it still occurs with all other mods disabled except palladium, and also confirmed on a fresh NeoForge 21.1.66 singleplayer game with only palladium (+ToadLib) installed.

### Steps to reproduce

1. Fence in some area
2. Spawn two villagers
3. Place three beds
4. Shower them in bread
5. Observe that they're picking up the bread and maybe kinda looking at each other but not breeding, no matter how much bread they get or how long you wait.
6. Optionally, exit game, disable palladium, restart game, and watch villagers start breeding soon after.

### What version of the palladium are you using?

1.0.9

**Comment by 64-bitman** [comment]
also prevents iron farms from working properly for me (villagers don't sleep despite having a bed in front of them) + removing a bed that a villager has claimed doesn't update their status (From what I found using carpet mod)

**Comment by ITsMrToad** [comment]
In 1.0.9.2, I tried to fix this.

**Comment by frgthyjuierjk** [comment]
This problem still persists and hasn't been fixed (Minecraft version 1.21.1)
I've made a fabric instance only using this mod (and the two dependencies it asks for) and the problem still occours.

The villagers get close to each other, but **they never breed**. 
When I disable the mod, it instantly works and the breeding happens.

Also, the villagers don't seem to update their status when a bed is removed. I've done it thinking I messed up a farm, and noticed they never changed their status (no particles displayed when I break and place a new bed).

Using:
- Fabric (v0.16.7)
- Palladium (v1.0.9.3)
- Fabric API (v0.106+1.21.1) 
  - also tried the newest version: v0.107+1.21.1
- toadlib (v1.1.6)

**Comment by ITsMrToad** [comment]
> This problem still persists and hasn't been fixed (Minecraft version 1.21.1) I've made a fabric instance only using this mod (and the two dependencies it asks for) and the problem still occours.
> 
> The villagers get close to each other, but **they never breed**. When I disable the mod, it instantly works and the breeding happens.
> 
> Also, the villagers don't seem to update their status when a bed is removed. I've done it thinking I messed up a farm, and noticed they never changed their status (no particles displayed when I break and place a new bed).
> 
> Using:
> 
> * Fabric (v0.16.7)
> * Palladium (v1.0.9.3)
> * Fabric API (v0.106+1.21.1)
>   
>   * also tried the newest version: v0.107+1.21.1
> * toadlib (v1.1.6)

Fixed in [1.0.9.5](https://modrinth.com/mod/mpalladium/version/1.0.9.4-1.21x-Fabric)
