### ISSUE TITLE
Crashes with Xaero's world map when zooming out

### ISSUE THREAD

**Issue by Enny777** [ITsMrToad/PalladiumMod#48]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

The game crashes when you zoom out in Xaero's world map.

### Steps to reproduce

Wait a few seconds for the chunks to load after entering the world.
Open the world map and zoom out.

### What version of the palladium are you using?

1.0.7

**Comment by ITsMrToad** [comment]
Send crash-log.
