### ISSUE TITLE
Crash a few seconds after entering the world

### ISSUE THREAD

**Issue by Tapacywka** [ITsMrToad/PalladiumMod#49]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

NeoForge

### Describe the bug

Crash a few seconds after entering the world.
Here is the latest.log with crash-report: https://mclo.gs/kerUYtW.

### Steps to reproduce

1. Install Minecraft 1.21.1 with NeoForge Loader 21.1.66.
2. Install Palladium 1.0.9 for NeoForge.
3. Enter the world and move around for a few seconds.

### What version of the palladium are you using?

1.0.9

**Comment by ITsMrToad** [comment]
Fixed in 1.0.9.2
