### ISSUE TITLE
[Visual Bug] [Neo] Blackscreen when Legacy 4J is installed

### ISSUE THREAD

**Issue by Cixon** [ITsMrToad/PalladiumMod#52]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

NeoForge

### Describe the bug

Joined a pre-existing world, got black screen. Very odd behavior.

Demonstration:
https://github.com/user-attachments/assets/d6162a21-4b3c-4d55-9c1a-d5a3802abcda

Mod Link:
https://modrinth.com/mod/legacy4j

Additionally, I noticed when I disabled Legacy 4J, the black screen was gone however I received a bunch of ticking errors...not sure what this is about? Made seperate ticket for this. See #53  .

### What version of the palladium are you using?

NeoForge - 1.0.9

**Comment by ITsMrToad** [comment]
Try disable 'Model verticies de-deduplication' (4J)

**Comment by Cixon** [comment]
> Try disable 'Model verticies de-deduplication' (4J)

how would i go about doing this?

**Comment by ITsMrToad** [comment]
> > Try disable 'Model verticies de-deduplication' (4J)
> 
> how would i go about doing this?

While the in-game config is not currently available, you can still use the regular one.

In the “config” folder you should find palladium-config.json (if it is not there, you should create it and put empty`{}`) inside the brackets look for/create `“enableShaderUniformCaching”` and `“enableQuadsDedup”` and set them to `false`.

**Comment by Cixon** [comment]
> > > Try disable 'Model verticies de-deduplication' (4J)
> > 
> > 
> > how would i go about doing this?
> 
> While the in-game config is not currently available, you can still use the regular one.
> 
> In the “config” folder you should find palladium-config.json (if it is not there, you should create it and put empty`{}`) inside the brackets look for/create `“enableShaderUniformCaching”` and `“enableQuadsDedup”` and set them to `false`.

## Black screen fixed. Just experiencing issue ticket 53.

# Demonstration:
![2024-10-12 13_57_37-Greenshot](https://github.com/user-attachments/assets/ad05543b-93cf-4834-832d-727868b65af1)
