### ISSUE TITLE
[Tick Exception] [Neo] Client crashes constantly without Neruina's guidance

### ISSUE THREAD

**Issue by Cixon** [ITsMrToad/PalladiumMod#53]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

NeoForge

### Describe the bug

There's a bunch of entity ticking errors that occurs when Palladium is installed.
As mentioned in #52 , I noticed a lot of strange behavior but no crashes, although if it wasn't for Neruina I probably would have.

Here's the log:
[latest.log](https://github.com/user-attachments/files/17348576/latest.log)

Crash-report (disabled Neruina):
[crash-2024-10-11_21.44.29-server.txt](https://github.com/user-attachments/files/17348579/crash-2024-10-11_21.44.29-server.txt)

### What version of the palladium are you using?

NeoForge - 1.0.9

**Comment by Cixon** [comment]
Additional context, this was tested on a pre-existing world.
All mods prior to installing Palladium in my pack worked just fine with 0 bugs and/or noticeable compromises.

**Comment by Cixon** [comment]
Setting `"lightweightWolfAndRabbitFleeAi"` to `false` seems to temporarily fix the problem... i could be wrong.

**Comment by ITsMrToad** [comment]
> Setting `"lightweightWolfAndRabbitFleeAi"` to `false` seems to temporarily fix the problem... i could be wrong.

Patch 1.0.9.2 probably fixed it.
