### ISSUE TITLE
[ALPHA] Missing Mixen Error

### ISSUE THREAD

**Issue by KateReller** [ITsMrToad/PalladiumMod#54]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

Game crashes on launch. 

Error log:
https://mclo.gs/GDwTFdo

### What version of the palladium are you using?

Palladium-1.20-1.20.4-1.0.9.2

**Comment by ITsMrToad** [comment]
Fixed in 1.0.9.3
