### ISSUE TITLE
[Neo] [1.21.1] Mob mayhem - Entities attack everything

### ISSUE THREAD

**Issue by Cixon** [ITsMrToad/PalladiumMod#55]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

NeoForge

### I heard explosions multiple times which I thought was strange. I go in spectator and see this:
https://streamable.com/m62xmk

### What version of the palladium are you using?

NeoForge - 1.0.9

**Comment by Cixon** [comment]
Setting `"lightweightWolfAndCatAttackAi"` to `false`  temporarily fix the problem.

**Comment by ITsMrToad** [comment]
Fixed in 1.0.9.3
