### ISSUE TITLE
some information about palladium (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [ITsMrToad/PalladiumMod#58]
### Question

hi, id like to know some infos about this cool mod,
what specific optimizations does it apply? would it benefit fps /entity lag? and does it improve shaders fps somehow with cache or sum stuff? should i use it in a 400+ mods modpack? would it benefit the pack somehow?

**Comment by ITsMrToad** [comment]
> What specific optimizations does it apply?

Deduplication, shader unifrom, integer, ilog cache, mob ai improvements and other small fixes

> Would it benefit fps /entity lag?

Fps gain, tps stabilization is there, but this gain depends on pc configuration

> Does it improve fps with shaders?

Logically, yes, I can't test it.

> Should i use it in a 400+ mods modpack? 

Of course, modern versions of palladium are compatible and stable(sort of).

> Would it benefit the pack somehow?

FPS will increase, TPS will stabilize.


If you have any problems, you can report them here and I will try to solve them even on a half-dead PC

**Comment by VaporeonScripts** [comment]
Alright ,ima run some tests with and without the mod,ty!

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/9a471711-6f74-44fd-933e-b23d716e086b)
btw theres a typo: a double oo on 'resource'

**Comment by ITsMrToad** [comment]
Oh, will be fixed, thanks.
