### ISSUE TITLE
FerriteCore Compat

### ISSUE THREAD

**Issue by D4RKAR117** [ITsMrToad/PalladiumMod#6]
The game crashes when palladium is installed alongside ferritecore due to neighbor table population (Self diagnostics says so).  A workaround is to turn on the `populateNeighborTable` option on ferritecore config `ferritecore-mixin.toml`

Crash log on startup: https://mclo.gs/oMVjBwT

**Comment by Krimatoria** [comment]
> The game crashes when palladium is installed alongside ferritecore due to neighbor table population (Self diagnostics says so). A workaround is to turn on the `populateNeighborTable` option on ferritecore config `ferritecore-mixin.toml`
> 
> Crash log on startup: https://mclo.gs/oMVjBwT

Yes, I also have an incompatibility with this mod 
https://gist.github.com/Krimatoria/04bffce75f44289ea971aac3ffdabd31

. I found another one, but while I'm trying to find which one, the download is breaking. 1.20.1

**Comment by ITsMrToad** [comment]
Will be fixed in 1.0.0.
