### ISSUE TITLE
unable to load on neoforge server 1.21.1 .72

### ISSUE THREAD

**Issue by VaporeonScripts** [ITsMrToad/PalladiumMod#60]
### What operating systems are you seeing the problem on?

Linux

### What the loader are you seeing the problem on?

NeoForge

### Describe the bug

https://mclo.gs/gmEFB1C

### Steps to reproduce

add the mod to server mods folder

### What version of the palladium are you using?

latest

**Comment by ITsMrToad** [comment]
Palladium is not yet possible to run on the server(It needs both sides).
