### ISSUE TITLE
Vertex de-duplication breaks mob and block rendering

### ISSUE THREAD

**Issue by MikiP98** [ITsMrToad/PalladiumMod#64]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

While vertex de-duplication is enabled mobs render in their own space dimension and some blocks (e.g. diagonal walls from a mod with the same name) render incorrectly (in the walls case, they are rotated by 45 deg)  
I will send SS tomorrow if I remember.

### Steps to reproduce

Hopefully install the mod, alongside lets say the previously mentioned diagonal walls and see the bug.  
I have over 300 mods and I really hope I won't need to binary search through them...

I've also had shader active, in-dev Bliss using Iris 1.7.5, but I don't remember if I also tested without them or not.

### What version of the palladium are you using?

1.0.9.2

**Comment by ITsMrToad** [comment]
Disable vertex de-duplication. It is highly unstable, and therefore can break vertexes
