### ISSUE TITLE
create mod render incorrectly

### ISSUE THREAD

**Issue by realomg** [ITsMrToad/PalladiumMod#66]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

Blocks in create mod render incorrectly when running with create mod
<img width="1280" alt="屏幕截图 2024-11-08 210217" src="https://github.com/user-attachments/assets/2435a2d7-f0eb-41b1-9b3c-9bbc7c867c3b">

### What version of the palladium are you using?

Palladium-1.20-1.20.4-1.0.9.3 (Minecraft 1.20.1)

**Comment by ITsMrToad** [comment]
Try disable 'Model verticies deduplication'

**Comment by 0Soulbolt** [comment]
> Try disable 'Model verticies deduplication'

Hello, i have found the same rendering issue, where can i disable the Model verticies deduplication setting, to see if that'd work?

**Comment by ITsMrToad** [comment]
>  Where can i disable the Model verticies deduplication?

Via in-game (not available on neoforge)/text config.

**Comment by 0Soulbolt** [comment]
I cant seem to find the config file nor can I open configs in-game, maybe because I use Tlauncher? idk

**Comment by ITsMrToad** [comment]
For in-game config you need to install embeddium.

**Comment by 0Soulbolt** [comment]
That seems to fix it yeah, ty. What purpose does verticies de-duplication serve, what does it do?

**Comment by ITsMrToad** [comment]
> That seems to fix it yeah, ty. What purpose does verticies de-duplication serve, what does it do?

The name speaks for itself, removes identical vertices, but either it doesn't work completely correctly (if so, I'll try to fix it in 1.1.0), or some models need identical vertices to display correctly.
