### ISSUE TITLE
Version support strategy?

### ISSUE THREAD

**Issue by ZZZank** [ITsMrToad/PalladiumMod#67]
### Question

Will you port Palladium to older versions of Minecraft (in my case, 1.16)? And if not, can I make an unofficial port and publish it?

**Comment by ITsMrToad** [comment]
> Will you port Palladium to older versions of Minecraft (in my case, 1.16)?

Don't know yet if there will be a port to older versions.

> And if not, can I make an unofficial port and publish it?

Sure, just leave a link to the original in the description
