### ISSUE TITLE
Diagonal Fences/Panes

### ISSUE THREAD

**Issue by lanwoodall423** [ITsMrToad/PalladiumMod#8]
1.20.1 Fabric
Any chance this mod is causing my fences and panes to all be diagonal suddenly? Also using diagonal fences/walls/etc mods

"StateHolder controls property(waterlogged, facing, etc.) of blockstates."

**Comment by ITsMrToad** [comment]
If you use `Diagonal fences` mod, it replace all fences with diagonal fences, regardless of Palladium

**Comment by lanwoodall423** [comment]
Yes I'm sorry to be more specific, I mean all of the fences and glass panes (maybe other things) are all oriented diagonally facing the same direction. Fences no longer connect, they are all facing the same way

**Comment by ITsMrToad** [comment]
Send log

**Comment by lanwoodall423** [comment]
[latest.log](https://github.com/user-attachments/files/16756306/latest.log)

**Comment by ITsMrToad** [comment]
Try disable Concurrent Chunk Management Engine(C2ME) or Apotheosis. 
Why you're using JEI and EMI at the same time?

**Comment by lanwoodall423** [comment]
My understanding is EMI pulls JEI recipes and disables JEI interface when it's present in the case a mod is JEI compatible but not EMI.

**Comment by ITsMrToad** [comment]
Ok. Disabling apotheosis/c2me produced any results?

**Comment by soup587** [comment]
issue happens with just diagonal fences/panes and palladium
![image](https://github.com/user-attachments/assets/66b5e87f-593b-4d9a-9400-9497cc31ccbe)

**Comment by ITsMrToad** [comment]
It's a texture error, disable ``Model verticies deduplication‘’.
