### ISSUE TITLE
IMPORTANT! Update to 1.0.0

### ISSUE THREAD

**Issue by ITsMrToad** [ITsMrToad/PalladiumMod#9]
When you update Palladium to 1.0.0 you will need to delete the old config(```config/palladium_config.json```) file otherwise it will crash!

**Comment by Viperwow** [comment]
Hi,

I'm making a performance modpack and am pretty interested in your mod to try. Do you have any plans for the 1.0+ release for Fabric? Would you like us to wait for it?

**Comment by ITsMrToad** [comment]
> Hi,
> 
> I'm making a performance modpack and am pretty interested in your mod to try. Do you have any plans for the 1.0+ release for Fabric? Would you like us to wait for it?

Fabirc 1.0.2 today
